id: A664477FB
title: Prayer
type: translation
pechas:
- I197E777E
- I08287533
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:36.262526
  last_modified_at: 2023-01-04 11:51:36.262538
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I197E777E/8986: 09F3
  I08287533/9C2E: 09F3
